[package]
name = "gittracker-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }
walkdir = "2.5.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
